version: '3'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build: ./docker/php
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www/html

  postgres:
    build: ./docker/postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
